definitions:
  env_unity: &env_unity
    groups:
    # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
      - unity # <-- (Includes UNITY_VERSION, UNITY_SERIAL, UNITY_USERNAME and UNITY_PASSWORD)
    vars:
      UNITY_BIN: /Applications/Unity/Hub/Editor/2020.3.31f1/Unity.app/Contents/MacOS/Unity
workflows:
  mac-mini-unity-2020:
    name: Mac Unity 2020
    max_build_duration: 120
    environment:
      <<: *env_unity
    scripts:
        - &activate_unity_license
          name: Activate License
          script: ${UNITY_BIN} -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
        - &build_app
          name: Build
          script: ${UNITY_BIN} -batchmode -quit -logFile -projectPath . -executeMethod BuildScript.BuildMac -nographics
    artifacts:
        - &app build/*.app
    publishing:
      scripts:
        - &deactivate_unity_license
          name: Deactivate License
          script: ${UNITY_BIN} -batchmode -quit -returnlicense -nographics
  mac-mini-m1-unity-2020:
    name: Mac (M1) Unity 2020
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      <<: *env_unity
    scripts:
        - name: Install Unity 2020
          script: | 
            curl -o ./unity.pkg https://download.unity3d.com/download_unity/6b54b7616050/MacEditorInstaller/Unity.pkg
            sudo -S installer -package ./unity.pkg -target / -verbose
            curl -o ./unity-mac.pkg https://download.unity3d.com/download_unity/6b54b7616050/MacEditorTargetInstaller/UnitySetup-Mac-Mono-Support-for-Editor-2020.3.31f1.pkg
            sudo -S installer -package ./unity-mac.pkg -target / -verbose
        - *activate_unity_license
        - *build_app
    artifacts:
        - *app
    publishing:
      scripts:
        - *deactivate_unity_license
  